name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger on push to the 'main' branch
  pull_request:
    branches:
      - main  # Trigger on pull request to 'main' branch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # Checkout the code
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'  # Set Python version to 3.9
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install Python dependencies from requirements.txt
          
      - name: Run tests with Pytest
        run: pytest  # Run tests using Pytest

  build-and-push-docker:
    needs: test  # Ensure this job runs after the test job is completed successfully
    runs-on: ubuntu-latest
    environment: production  # Use the production environment for deployment
    steps:
      - uses: actions/checkout@v4  # Checkout the code
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3  # Set up Docker Buildx for multi-platform builds
      
      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}  # Docker Hub username stored in GitHub Secrets
          password: ${{ secrets.DOCKERHUB_TOKEN }}    # Docker Hub token stored in GitHub Secrets
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true  # Push the Docker image to Docker Hub
          tags: yyepezx96/devops_demo:latest  # Replace with your DockerHub username and repository name

          # Additional Docker build arguments (optional)
          context: .  # Path to the Docker context (current directory)
          file: ./Dockerfile  # Path to the Dockerfile (make sure it's in the correct location)

